export const data = [
  {
    newJoinCount: '3869',
    locationPlanRate: '69.74%',
    conversionRateRed: false,
    aveLocationDays: '35天',
    locationCount: '1916',
    locationRateRed: false,
    chooseSpotCount: '3141',
    locationPlanRateRed: false,
    passRate: '55.31%',
    conversionRate: '80.3%',
    passCount: '2427',
    locationRate: '69.55%',
    spotReportRateRed: false,
    aveLocationDaysRed: false,
    name: '/',
    devDpt: '全国',
    id: '1',
    newSpotCount: '15705',
    spotReportRate: '87.91%',
    passRateRed: false,
  },
  {
    newJoinCount: '184',
    locationPlanRate: '74.15%',
    conversionRateRed: false,
    aveLocationDays: '36天',
    locationCount: '65',
    locationRateRed: false,
    chooseSpotCount: '150',
    locationPlanRateRed: false,
    passRate: '58.67%',
    conversionRate: '81.52%',
    passCount: '88',
    locationRate: '73.86%',
    spotReportRateRed: false,
    aveLocationDaysRed: true,
    name: '夏子赢',
    devDpt: '华东区',
    id: '2',
    newSpotCount: '750',
    spotReportRate: '98.37%',
    passRateRed: false,
  },
  {
    newJoinCount: '197',
    locationPlanRate: '84.30%',
    conversionRateRed: false,
    aveLocationDays: '29天',
    locationCount: '78',
    locationRateRed: false,
    chooseSpotCount: '163',
    locationPlanRateRed: false,
    passRate: '61.96%',
    conversionRate: '82.74%',
    passCount: '101',
    locationRate: '77.23%',
    spotReportRateRed: false,
    aveLocationDaysRed: false,
    name: '姜营',
    devDpt: '华南区',
    id: '3',
    newSpotCount: '815',
    spotReportRate: '89.46%',
    passRateRed: false,
  },
  {
    newJoinCount: '164',
    locationPlanRate: '66.25%',
    conversionRateRed: true,
    aveLocationDays: '38天',
    locationCount: '45',
    locationRateRed: true,
    chooseSpotCount: '130',
    locationPlanRateRed: true,
    passRate: '52.31%',
    conversionRate: '79.27%',
    passCount: '68',
    locationRate: '66.18%',
    spotReportRateRed: false,
    aveLocationDaysRed: true,
    name: '秦野',
    devDpt: '华中区',
    id: '4',
    newSpotCount: '650',
    spotReportRate: '90.22%',
    passRateRed: true,
  },
  {
    newJoinCount: '151',
    locationPlanRate: '69.78%',
    conversionRateRed: false,
    aveLocationDays: '34天',
    locationCount: '32',
    locationRateRed: false,
    chooseSpotCount: '117',
    locationPlanRateRed: true,
    passRate: '47.01%',
    conversionRate: '77.48%',
    passCount: '55',
    locationRate: '58.18%',
    spotReportRateRed: true,
    aveLocationDaysRed: false,
    name: '周鹏',
    devDpt: '华北区',
    id: '5',
    newSpotCount: '585',
    spotReportRate: '86.32%',
    passRateRed: false,
  },
  {
    newJoinCount: '180',
    locationPlanRate: '55.89%',
    conversionRateRed: true,
    aveLocationDays: '42天',
    locationCount: '61',
    locationRateRed: true,
    chooseSpotCount: '146',
    locationPlanRateRed: true,
    passRate: '57.53%',
    conversionRate: '81.11%',
    passCount: '84',
    locationRate: '72.62%',
    spotReportRateRed: true,
    aveLocationDaysRed: true,
    name: '顾鑫',
    devDpt: '西南区',
    id: '6',
    newSpotCount: '730',
    spotReportRate: '77.27%',
    passRateRed: true,
  },
  {
    newJoinCount: '177',
    locationPlanRate: '49.61%',
    conversionRateRed: false,
    aveLocationDays: '37天',
    locationCount: '58',
    locationRateRed: false,
    chooseSpotCount: '143',
    locationPlanRateRed: true,
    passRate: '56.64%',
    conversionRate: '80.79%',
    passCount: '81',
    locationRate: '71.60%',
    spotReportRateRed: false,
    aveLocationDaysRed: true,
    name: '李利',
    devDpt: '西北区',
    id: '7',
    newSpotCount: '715',
    spotReportRate: '91.57%',
    passRateRed: false,
  },
  {
    newJoinCount: '166',
    locationPlanRate: '88.22%',
    conversionRateRed: true,
    aveLocationDays: '44天',
    locationCount: '47',
    locationRateRed: true,
    chooseSpotCount: '132',
    locationPlanRateRed: false,
    passRate: '53.03%',
    conversionRate: '79.52%',
    passCount: '70',
    locationRate: '67.14%',
    spotReportRateRed: true,
    aveLocationDaysRed: true,
    name: '申凯',
    devDpt: '东北区',
    id: '8',
    newSpotCount: '660',
    spotReportRate: '82.13%',
    passRateRed: true,
  },
];
