// 各区域完成情况
export const completionList = [
  {
    'id': 1,
    'devDpt': '全国',
    'inOperationStoresCount': 3938,
    'inOperationStoresCountRed': false,
    'newStoresCount': 1469,
    'newStoresCountRed': false,
    'locationPlanRate': '69.74%',
    'locationPlanRateRed': false,
    'spotReportRate': '87.91%',
    'spotReportRateRed': false,
    'locationCount': 1916,
    'locationRate': '77.64%',
    'locationRateRed': false,
    'passCount': 2427,
    'passRate': '76.45%',
    'passRateRed': false,
    'chooseSpotCount': 3141,
    'conversionRate': '80.7%',
    'conversionRateRed': false,
    'newJoinCount': 3869,
    'newSpotCount': 15705,
    'storeSpotCount': 32950,
    'aveLocationDays': '35天',
    'aveLocationDaysRed': false
  },
  {
    'id': 2,
    'devDpt': '华东区',
    'inOperationStoresCount': 637,
    'inOperationStoresCountRed': false,
    'newStoresCount': 213,
    'newStoresCountRed': false,
    'locationPlanRate': '74.15%',
    'locationPlanRateRed': false,
    'spotReportRate': '98.37%',
    'spotReportRateRed': false,
    'locationCount': 295,
    'locationRate': '80.16%',
    'locationRateRed': false,
    'passCount': 368,
    'passRate': '78.30%',
    'passRateRed': false,
    'chooseSpotCount': 470,
    'conversionRate': '81.88%',
    'conversionRateRed': false,
    'newJoinCount': 574,
    'newSpotCount': 2350,
    'storeSpotCount': 4935,
    'aveLocationDays': '36天',
    'aveLocationDaysRed': true
  },
  {
    'id': 3,
    'devDpt': '华南区',
    'inOperationStoresCount': 882,
    'inOperationStoresCountRed': false,
    'newStoresCount': 332,
    'newStoresCountRed': false,
    'locationPlanRate': '84.30%',
    'locationPlanRateRed': false,
    'spotReportRate': '89.46%',
    'spotReportRateRed': false,
    'locationCount': 378,
    'locationRate': '83.81%',
    'locationRateRed': false,
    'passCount': 451,
    'passRate': '81.56%',
    'passRateRed': false,
    'chooseSpotCount': 553,
    'conversionRate': '84.17%',
    'conversionRateRed': false,
    'newJoinCount': 657,
    'newSpotCount': 2765,
    'storeSpotCount': 5808,
    'aveLocationDays': '29天',
    'aveLocationDaysRed': false
  },
  {
    'id': 4,
    'devDpt': '华中区',
    'inOperationStoresCount': 468,
    'inOperationStoresCountRed': false,
    'newStoresCount': 124,
    'newStoresCountRed': true,
    'locationPlanRate': '66.25%',
    'locationPlanRateRed': true,
    'spotReportRate': '90.22%',
    'spotReportRateRed': false,
    'locationCount': 155,
    'locationRate': '67.98%',
    'locationRateRed': true,
    'passCount': 228,
    'passRate': '69.09%',
    'passRateRed': true,
    'chooseSpotCount': 330,
    'conversionRate': '76.04%',
    'conversionRateRed': true,
    'newJoinCount': 434,
    'newSpotCount': 1650,
    'storeSpotCount': 3465,
    'aveLocationDays': '38天',
    'aveLocationDaysRed': true
  },
  {
    'id': 5,
    'devDpt': '华北区',
    'inOperationStoresCount': 679,
    'inOperationStoresCountRed': false,
    'newStoresCount': 322,
    'newStoresCountRed': false,
    'locationPlanRate': '69.78%',
    'locationPlanRateRed': true,
    'spotReportRate': '86.32%',
    'spotReportRateRed': true,
    'locationCount': 402,
    'locationRate': '84.63%',
    'locationRateRed': false,
    'passCount': 475,
    'passRate': '82.32%',
    'passRateRed': false,
    'chooseSpotCount': 577,
    'conversionRate': '84.73%',
    'conversionRateRed': false,
    'newJoinCount': 681,
    'newSpotCount': 2885,
    'storeSpotCount': 6012,
    'aveLocationDays': '34天',
    'aveLocationDaysRed': false
  },
  {
    'id': 6,
    'devDpt': '西南区',
    'inOperationStoresCount': 542,
    'inOperationStoresCountRed': false,
    'newStoresCount': 178,
    'newStoresCountRed': false,
    'locationPlanRate': '55.89%',
    'locationPlanRateRed': true,
    'spotReportRate': '77.27%',
    'spotReportRateRed': true,
    'locationCount': 231,
    'locationRate': '75.99%',
    'locationRateRed': true,
    'passCount': 304,
    'passRate': '74.88%',
    'passRateRed': true,
    'chooseSpotCount': 406,
    'conversionRate': '79.61%',
    'conversionRateRed': true,
    'newJoinCount': 510,
    'newSpotCount': 2030,
    'storeSpotCount': 4263,
    'aveLocationDays': '42天',
    'aveLocationDaysRed': true
  },
  {
    'id': 7,
    'devDpt': '西北区',
    'inOperationStoresCount': 321,
    'inOperationStoresCountRed': true,
    'newStoresCount': 167,
    'newStoresCountRed': false,
    'locationPlanRate': '49.61%',
    'locationPlanRateRed': true,
    'spotReportRate': '91.57%',
    'spotReportRateRed': false,
    'locationCount': 258,
    'locationRate': '77.95%',
    'locationRateRed': false,
    'passCount': 331,
    'passRate': '76.44%',
    'passRateRed': false,
    'chooseSpotCount': 433,
    'conversionRate': '80.63%',
    'conversionRateRed': false,
    'newJoinCount': 537,
    'newSpotCount': 2165,
    'storeSpotCount': 4561,
    'aveLocationDays': '37天',
    'aveLocationDaysRed': true
  },
  {
    'id': 8,
    'devDpt': '东北区',
    'inOperationStoresCount': 409,
    'inOperationStoresCountRed': false,
    'newStoresCount': 133,
    'newStoresCountRed': true,
    'locationPlanRate': '88.22%',
    'locationPlanRateRed': false,
    'spotReportRate': '82.13%',
    'spotReportRateRed': true,
    'locationCount': 197,
    'locationRate': '72.96%',
    'locationRateRed': true,
    'passCount': 270,
    'passRate': '72.58%',
    'passRateRed': true,
    'chooseSpotCount': 372,
    'conversionRate': '78.15%',
    'conversionRateRed': true,
    'newJoinCount': 476,
    'newSpotCount': 1860,
    'storeSpotCount': 3906,
    'aveLocationDays': '44天',
    'aveLocationDaysRed': true
  }
];
// 重点推进项目
export const PromotionProjectsList = [
  {
    'id': 1,
    'joinCity': '上海市',
    'joinCode': 'KF20221213',
    'joinName': '李雷',
    'currentStatus': '门店评估',
    'matchSpotNum': '龙之梦3楼3006',
    'storeType': '商场门店',
    'dailySales': '21560',
    'dailyCost': '10122',
    'profitRate': '66.78%',
    'joinDate': '2022/12/13',
    'locationDaysStr': '70天+',
    'locationDaysStrRed': true
  },
  {
    'id': 2,
    'joinCity': '北京市',
    'joinCode': 'KF20230218',
    'joinName': '韩峰',
    'currentStatus': '点位匹配',
    'matchSpotNum': '合生汇负1楼B1007',
    'storeType': '大客流店',
    'dailySales': '30225',
    'dailyCost': '18903',
    'profitRate': '56.72%',
    'joinDate': '2023/2/18',
    'locationDaysStr': '20天+',
    'locationDaysStrRed': false
  },
  {
    'id': 3,
    'joinCity': '杭州市',
    'joinCode': 'KF20230210',
    'joinName': '余浩',
    'currentStatus': '待签约',
    'matchSpotNum': '阿里西溪园区507',
    'storeType': '办公园区店',
    'dailySales': '14226',
    'dailyCost': '8904',
    'profitRate': '43.55%',
    'joinDate': '2023/2/10',
    'locationDaysStr': '30天+',
    'locationDaysStrRed': false
  },
  {
    'id': 4,
    'joinCity': '南京市',
    'joinCode': 'KF20230120',
    'joinName': '毛冰',
    'currentStatus': '已签约',
    'matchSpotNum': '威尼斯水城第三街区213号',
    'storeType': '社区邻里店',
    'dailySales': '10227',
    'dailyCost': '6905',
    'profitRate': '77.12%',
    'joinDate': '2023/1/20',
    'locationDaysStr': '25天',
    'locationDaysStrRed': false
  },
  {
    'id': 5,
    'joinCity': '广州市',
    'joinCode': 'KF20230215',
    'joinName': '李栋',
    'currentStatus': '待签约',
    'matchSpotNum': '正佳广场2楼237号',
    'storeType': '商场门店',
    'dailySales': '33228',
    'dailyCost': '21906',
    'profitRate': '59.23%',
    'joinDate': '2023/2/15',
    'locationDaysStr': '18天+',
    'locationDaysStrRed': false
  },
  {
    'id': 6,
    'joinCity': '深圳市',
    'joinCode': 'KF20230222',
    'joinName': '周权',
    'currentStatus': '点位匹配',
    'matchSpotNum': '腾讯总部322号',
    'storeType': '办公园区店',
    'dailySales': '20229',
    'dailyCost': '18907',
    'profitRate': '61.78%',
    'joinDate': '2023/2/22',
    'locationDaysStr': '8天+',
    'locationDaysStrRed': false
  }
];
// 漏斗数据
export const funnelList = [
  {
    'devDpt': '全国',
    'newSpotCount': 15705,
    'newFranchiseeCount': 3869,
    'chooseSpotCount': 3141,
    'passCount': 2427,
    'locationCount': 1916
  },
  {
    'devDpt': '华东区',
    'newSpotCount': 2350,
    'newFranchiseeCount': 574,
    'chooseSpotCount': 470,
    'passCount': 368,
    'locationCount': 295
  },
  {
    'devDpt': '华南区',
    'newSpotCount': 2765,
    'newFranchiseeCount': 657,
    'chooseSpotCount': 553,
    'passCount': 451,
    'locationCount': 378
  },
  {
    'devDpt': '华中区',
    'newSpotCount': 1650,
    'newFranchiseeCount': 434,
    'chooseSpotCount': 330,
    'passCount': 228,
    'locationCount': 155
  },
  {
    'devDpt': '华北区',
    'newSpotCount': 2885,
    'newFranchiseeCount': 681,
    'chooseSpotCount': 577,
    'passCount': 475,
    'locationCount': 402
  },
  {
    'devDpt': '西南区',
    'newSpotCount': 2030,
    'newFranchiseeCount': 510,
    'chooseSpotCount': 406,
    'passCount': 304,
    'locationCount': 231
  },
  {
    'devDpt': '西北区',
    'newSpotCount': 2165,
    'newFranchiseeCount': 537,
    'chooseSpotCount': 433,
    'passCount': 331,
    'locationCount': 258
  },
  {
    'devDpt': '东北区',
    'newSpotCount': 1860,
    'newFranchiseeCount': 476,
    'chooseSpotCount': 372,
    'passCount': 270,
    'locationCount': 197
  }
];
