export const data = [
  {
    id: 1,
    joinDate: '2022/12/13',
    locationDays: '70',
    locationDaysStr: '70天+',
    locationDaysRed: true,
    chooseSpot: '龙之梦3楼3006',
    joinName: '李雷',
    currentStatus: '门店评估',
    matchSpotNum: '3',
    feeStatus: '已收取',
    joinCode: 'KF20221213',
    responsibleName: '夏子赢',
    joinCity: '上海市',
    joinCityId: 73,
  },
  {
    id: 2,
    joinDate: '2023/2/18',
    locationDays: '20',
    locationDaysStr: '20天+',
    locationDaysRed: false,
    chooseSpot: '合生汇负1楼B1007',
    joinName: '韩峰',
    currentStatus: '点位匹配',
    matchSpotNum: '4',
    feeStatus: '已收取',
    joinCode: 'KF20230218',
    responsibleName: '姜营',
    joinCity: '北京市',
    joinCityId: 1,
  },
  {
    id: 3,
    joinDate: '2023/2/10',
    locationDays: '30',
    locationDaysStr: '30天+',
    locationDaysRed: false,
    chooseSpot: '阿里西溪园区507',
    joinName: '余浩',
    currentStatus: '待签约',
    matchSpotNum: '2',
    feeStatus: '已收取',
    joinCode: 'KF20230210',
    responsibleName: '秦野',
    joinCity: '杭州市',
    joinCityId: 87,
  },
  {
    id: 4,
    joinDate: '2023/1/20',
    locationDays: '25',
    locationDaysStr: '25天',
    locationDaysRed: false,
    chooseSpot: '威尼斯水城第三街区213号',
    joinName: '毛冰',
    currentStatus: '已签约',
    matchSpotNum: '5',
    feeStatus: '已收取',
    joinCode: 'KF20230120',
    responsibleName: '周鹏',
    joinCity: '南京市',
    joinCityId: 74,
  },
  {
    id: 5,
    joinDate: '2023/2/15',
    locationDays: '18',
    locationDaysStr: '18天+',
    locationDaysRed: false,
    chooseSpot: '正佳广场2楼237号',
    joinName: '李栋',
    currentStatus: '待签约',
    matchSpotNum: '2',
    feeStatus: '已收取',
    joinCode: 'KF20230215',
    responsibleName: '顾鑫',
    joinCity: '广州市',
    joinCityId: 199,
  },
  {
    id: 6,
    joinDate: '2023/2/22',
    locationDays: '8',
    locationDaysStr: '8天+',
    locationDaysRed: false,
    chooseSpot: '腾讯总部322号',
    joinName: '周权',
    currentStatus: '点位匹配',
    matchSpotNum: '6',
    feeStatus: '已收取',
    joinCode: 'KF20230222',
    responsibleName: '李利',
    joinCity: '深圳市',
    joinCityId: 201,
  },
];
export const PointMatchData = [
  {
    id: 1,
    reason: '最租金不满意',
    name: '白玉兰广场3楼3007',
    flow: '17823',
    rent: '38',
    area: '90',
    predictSale: '21560元',
    isChecked: '否',
    date: '2022/1/13',
    breakEvenSale: '10122元',
    city: '上海市',
    schedule: '暂停'
  },
  {
    id: 2,
    reason: '想找更大客流',
    name: '静安大悦城4楼4012',
    flow: '18763',
    rent: '29',
    area: '100',
    predictSale: '30225元',
    isChecked: '否',
    date: '2023/2/18',
    breakEvenSale: '18903元',
    city: '上海市',
    schedule: '暂停'
  },
  {
    id: 3,
    reason: '面积不合适',
    name: '北外滩来福士3楼3122',
    flow: '19887',
    rent: '33',
    area: '120',
    predictSale: '14226元',
    isChecked: '否',
    date: '2023/2/10',
    breakEvenSale: '8904元',
    city: '上海市',
    schedule: '暂停'
  },
  {
    id: 4,
    reason: '评估不通过',
    name: '旭辉MALL3楼3022',
    flow: '28312',
    rent: '56',
    area: '89',
    predictSale: '10227元',
    isChecked: '是',
    date: '2023/1/20',
    breakEvenSale: '6905元',
    city: '上海市',
    schedule: '暂停'
  },
  {
    id: 5,
    reason: null,
    name: '龙之梦3楼3006',
    flow: '23214',
    rent: '41',
    area: '105',
    predictSale: '33228元',
    isChecked: '是',
    date: '2023/2/15',
    breakEvenSale: '21906元',
    city: '上海市',
    schedule: '门店评估'
  }
];
