export const AppIconList = [
  { link: 'icon-ic_occupy' },
  { link: 'icon-ic_bi' },
  { link: 'icon-ic_yundian' },
  { link: 'icon-ic_approve' },
  { link: 'icon-ic_qianji' },
  { link: 'icon-ic_account' },
  { link: 'icon-ic_zhinengdingjia' },
  { link: 'icon-ic_dingdan' },
  { link: 'icon-ic_crm' },
  { link: 'icon-ic_shujudongcha' },
  { link: 'icon-ic_location' },
  { link: 'icon-ic_pms1' },
  { link: 'icon-ic_keliuyuce' },
  { link: 'icon-ic_caiwu' },
  { link: 'icon-renzheng1' },
  { link: 'icon-ic_keliu' },
  { link: 'icon-ic_tuodian' },
  { link: 'icon-ic_schedule' },
  { link: 'icon-ic_ziyuanzhongxin' },
];
