/**
 * @Description 列表数据
 */

/**
 * @description 个人绩效报表数据
 *
 *  参照console-pc /fishtogether/individualkpireport 页面
 * /zeus-api/api/yn/franchisee/form/person 接口的数据格式
 */
export const personalList = [
  {
    'departmentId': 0,
    'departmentName': '汇总',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': '46.67%',
    'contractAgreeCount': 7,
    'contractAgreeRate': '43.75%',
    'evaluationAgreeCount': 16,
    'evaluationAgreeRate': '25.4%',
    'evaluationCount': 63,
    'franchiseeCount': 31,
    'pointAllCount': 60,
    'chancePointCount': 60,
    'avgContractAgreePeriod': '7天',
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39349,
    'departmentName': '华西开发一区',
    'userName': '杨振军',
    'contractPlanCount': 3,
    'contractPlanRate': '66.67%',
    'contractAgreeCount': 2,
    'contractAgreeRate': '66.67%',
    'evaluationAgreeCount': 3,
    'evaluationAgreeRate': '15.79%',
    'evaluationCount': 19,
    'franchiseeCount': 6,
    'pointAllCount': 21,
    'chancePointCount': 21,
    'avgContractAgreePeriod': '2天',
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39349,
    'departmentName': '华西开发一区',
    'userName': '建国-华西一区2',
    'contractPlanCount': 3,
    'contractPlanRate': '0%',
    'contractAgreeCount': 0,
    'contractAgreeRate': '0%',
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': '0%',
    'evaluationCount': 5,
    'franchiseeCount': 4,
    'pointAllCount': 2,
    'chancePointCount': 2,
    'avgContractAgreePeriod': null,
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39349,
    'departmentName': '华西开发一区',
    'userName': '丁佳薇',
    'contractPlanCount': 3,
    'contractPlanRate': '133.33%',
    'contractAgreeCount': 4,
    'contractAgreeRate': '33.33%',
    'evaluationAgreeCount': 12,
    'evaluationAgreeRate': '34.29%',
    'evaluationCount': 35,
    'franchiseeCount': 19,
    'pointAllCount': 36,
    'chancePointCount': 36,
    'avgContractAgreePeriod': '12天',
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39349,
    'departmentName': '华西开发一区',
    'userName': '建国-华西一区',
    'contractPlanCount': 3,
    'contractPlanRate': '33.33%',
    'contractAgreeCount': 1,
    'contractAgreeRate': '100%',
    'evaluationAgreeCount': 1,
    'evaluationAgreeRate': '50%',
    'evaluationCount': 2,
    'franchiseeCount': 2,
    'pointAllCount': 0,
    'chancePointCount': 0,
    'avgContractAgreePeriod': null,
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39362,
    'departmentName': '华南开发部',
    'userName': '毛李香',
    'contractPlanCount': 3,
    'contractPlanRate': '0%',
    'contractAgreeCount': 0,
    'contractAgreeRate': '0%',
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': '0%',
    'evaluationCount': 2,
    'franchiseeCount': 0,
    'pointAllCount': 1,
    'chancePointCount': 1,
    'avgContractAgreePeriod': null,
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  }
];


/**
 * @description 开发部绩效报表数据
 *
 *  参照console-pc /fishtogether/devdptkpireport 页面
 * /zeus-api/api/yn/franchisee/form/department 接口的数据格式
 */
export const departList = [
  {
    'departmentId': 0,
    'departmentName': '全国',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': null,
    'contractAgreeCount': 7,
    'contractAgreeRate': '43.75%',
    'evaluationAgreeCount': 16,
    'evaluationAgreeRate': '25.40%',
    'evaluationCount': 63,
    'franchiseeCount': 31,
    'pointAllCount': 60,
    'chancePointCount': 60,
    'avgContractAgreePeriod': '2天',
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39362,
    'departmentName': '华南开发部',
    'userName': null,
    'contractPlanCount': 0,
    'contractPlanRate': '0%',
    'contractAgreeCount': 0,
    'contractAgreeRate': '0%',
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': '0%',
    'evaluationCount': 2,
    'franchiseeCount': 0,
    'pointAllCount': 1,
    'chancePointCount': 1,
    'avgContractAgreePeriod': null,
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39349,
    'departmentName': '华西开发一区',
    'userName': null,
    'contractPlanCount': 0,
    'contractPlanRate': '0%',
    'contractAgreeCount': 7,
    'contractAgreeRate': '43.75%',
    'evaluationAgreeCount': 16,
    'evaluationAgreeRate': '26.23%',
    'evaluationCount': 61,
    'franchiseeCount': 31,
    'pointAllCount': 59,
    'chancePointCount': 59,
    'avgContractAgreePeriod': '2天',
    'underPlanRate': null,
    'underContractAgreeRate': null,
    'underEvaluationAgreeRate': null,
    'overtopContractAgreePeriod': null
  },
  {
    'departmentId': 39358,
    'departmentName': '华中开发二区',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': null,
    'contractAgreeCount': 0,
    'contractAgreeRate': null,
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': null,
    'evaluationCount': 0,
    'franchiseeCount': 0,
    'pointAllCount': 0,
    'chancePointCount': 0,
    'avgContractAgreePeriod': null,
    'underPlanRate': 0,
    'underContractAgreeRate': 0,
    'underEvaluationAgreeRate': 0,
    'overtopContractAgreePeriod': 0
  },
  {
    'departmentId': 39357,
    'departmentName': '华中开发一区',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': null,
    'contractAgreeCount': 0,
    'contractAgreeRate': null,
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': null,
    'evaluationCount': 0,
    'franchiseeCount': 0,
    'pointAllCount': 0,
    'chancePointCount': 0,
    'avgContractAgreePeriod': null,
    'underPlanRate': 0,
    'underContractAgreeRate': 0,
    'underEvaluationAgreeRate': 0,
    'overtopContractAgreePeriod': 0
  },
  {
    'departmentId': 39350,
    'departmentName': '华西开发二区',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': null,
    'contractAgreeCount': 0,
    'contractAgreeRate': null,
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': null,
    'evaluationCount': 0,
    'franchiseeCount': 0,
    'pointAllCount': 0,
    'chancePointCount': 0,
    'avgContractAgreePeriod': null,
    'underPlanRate': 0,
    'underContractAgreeRate': 0,
    'underEvaluationAgreeRate': 0,
    'overtopContractAgreePeriod': 0
  },
  {
    'departmentId': 39342,
    'departmentName': '华东开发部',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': null,
    'contractAgreeCount': 0,
    'contractAgreeRate': null,
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': null,
    'evaluationCount': 0,
    'franchiseeCount': 0,
    'pointAllCount': 0,
    'chancePointCount': 0,
    'avgContractAgreePeriod': null,
    'underPlanRate': 0,
    'underContractAgreeRate': 0,
    'underEvaluationAgreeRate': 0,
    'overtopContractAgreePeriod': 0
  },
  {
    'departmentId': 39340,
    'departmentName': '华北开发二区',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': null,
    'contractAgreeCount': 0,
    'contractAgreeRate': null,
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': null,
    'evaluationCount': 0,
    'franchiseeCount': 0,
    'pointAllCount': 0,
    'chancePointCount': 0,
    'avgContractAgreePeriod': null,
    'underPlanRate': 0,
    'underContractAgreeRate': 0,
    'underEvaluationAgreeRate': 0,
    'overtopContractAgreePeriod': 0
  },
  {
    'departmentId': 39339,
    'departmentName': '华北开发一区',
    'userName': null,
    'contractPlanCount': null,
    'contractPlanRate': null,
    'contractAgreeCount': 0,
    'contractAgreeRate': null,
    'evaluationAgreeCount': 0,
    'evaluationAgreeRate': null,
    'evaluationCount': 0,
    'franchiseeCount': 0,
    'pointAllCount': 0,
    'chancePointCount': 0,
    'avgContractAgreePeriod': null,
    'underPlanRate': 0,
    'underContractAgreeRate': 0,
    'underEvaluationAgreeRate': 0,
    'overtopContractAgreePeriod': 0
  }
];
